### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wongsyrone** [fuckshadows/fuckshadows-libev#1]
TBD:

- [ ] https://github.com/shadowsocks/shadowsocks-libev/commit/54acbba2a7711d08a78df0eacb6e5e21a6530d48
- [ ] https://github.com/shadowsocks/shadowsocks-libev/commit/81006d4690cfbd04afabc176d2c1a3bb69a12808
- [ ] https://github.com/shadowsocks/shadowsocks-libev/commit/b918fd7a7772efe7d4cad3bbcb388f112140bd91
